[package]
name = "coliseum-net"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = "*"
sha256 = "1.5.0"
serde_json = "*"
serde = { version = "1.0.197", features = ["derive"] }
tokio = { version = "1", features = ["full"] }